definitions:
  domain.Users:
    properties:
      avatar:
        type: string
      created_on:
        type: string
      deteled:
        type: string
      id:
        type: integer
      password:
        type: string
      state:
        type: string
      user_type:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /user/info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Users'
      summary: 获取用户信息
      tags:
      - user
swagger: "2.0"
