// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package boot

import (
	"test_gin/app"
	"test_gin/app/api"
	"test_gin/app/repository"
	"test_gin/app/services"
	"test_gin/common/datasource"
	"test_gin/common/logger"
	"test_gin/common/middleware/jwt"
)

// Injectors from inject.go:

func Inject(source *datasource.Db, log *logger.Logger) *app.App {
	iUserRepository := repository.NewUserRepository(log, source)
	iRoleRepository := repository.NewRoleRepository(log, source)
	iUserService := service.NewUserService(iUserRepository, iRoleRepository, log)
	iRoleService := service.NewRoleService(iRoleRepository)
	jwtJWT := &jwt.JWT{
		UserService: iUserService,
		RoleService: iRoleService,
	}
	user := api.NewUser(log, jwtJWT, iUserService)
	appApp := &app.App{
		User: user,
	}
	return appApp
}
